# Generated by Django 4.1.1 on 2023-05-04 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=20)),
                (
                    "public_contact_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("public_num", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "public_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact1_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "contact1_num",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "contact1_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact2_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "contact2_num",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "contact2_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Mixed", "Mixed"),
                            ("Ladies", "Ladies"),
                            ("Mens", "Mens"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "level",
                    models.CharField(
                        choices=[("Ladies", "Ladies"), ("Mens", "Mens")], max_length=10
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="league.club"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("current", models.BooleanField()),
                ("archive_info", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=255)),
                ("map", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Mixed", "Mixed"),
                            ("Ladies", "Ladies"),
                            ("Mens", "Mens"),
                        ],
                        max_length=10,
                    ),
                ),
                ("number", models.IntegerField(default=1)),
                ("penalties", models.IntegerField(default=0)),
                ("captain", models.CharField(blank=True, max_length=30, null=True)),
                ("captain_num", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "captain_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="league.club"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="league.division",
                    ),
                ),
                (
                    "nom_player1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="np1",
                        to="league.player",
                    ),
                ),
                (
                    "nom_player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="np2",
                        to="league.player",
                    ),
                ),
                (
                    "nom_player3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="np3",
                        to="league.player",
                    ),
                ),
                (
                    "nom_player4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="np4",
                        to="league.player",
                    ),
                ),
                (
                    "nom_player5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="np5",
                        to="league.player",
                    ),
                ),
                (
                    "nom_player6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="np6",
                        to="league.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("home_points", models.IntegerField(blank=True, default=0, null=True)),
                ("away_points", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Unplayed", "Unplayed"),
                            ("Postponed", "Postponed"),
                            ("Proposed", "New Date Proposed"),
                            ("Rearranged", "Rearranged"),
                            ("Played", "Played"),
                            ("Conceded (H)", "Conceded (H)"),
                            ("Conceded (A)", "Conceded (A)"),
                        ],
                        default="Unplayed",
                        max_length=20,
                    ),
                ),
                ("old_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "game_results",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "away_player1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ap1",
                        to="league.player",
                    ),
                ),
                (
                    "away_player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ap2",
                        to="league.player",
                    ),
                ),
                (
                    "away_player3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ap3",
                        to="league.player",
                    ),
                ),
                (
                    "away_player4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ap4",
                        to="league.player",
                    ),
                ),
                (
                    "away_player5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ap5",
                        to="league.player",
                    ),
                ),
                (
                    "away_player6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ap6",
                        to="league.player",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away",
                        to="league.team",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league.division",
                    ),
                ),
                (
                    "home_player1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hp1",
                        to="league.player",
                    ),
                ),
                (
                    "home_player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hp2",
                        to="league.player",
                    ),
                ),
                (
                    "home_player3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hp3",
                        to="league.player",
                    ),
                ),
                (
                    "home_player4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hp4",
                        to="league.player",
                    ),
                ),
                (
                    "home_player5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hp5",
                        to="league.player",
                    ),
                ),
                (
                    "home_player6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hp6",
                        to="league.player",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home",
                        to="league.team",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="league.season"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="league.venue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="league.club"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
