# Generated by Django 4.1.1 on 2023-05-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="team",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
