# Generated by Django 4.1.1 on 2023-06-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0003_clubnight"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="blurb",
            field=models.TextField(blank=True, null=True),
        ),
    ]
