# Generated by Django 4.1.1 on 2023-06-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0004_club_blurb"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="contact1_landline",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="contact2_landline",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
