# Generated by Django 4.1.1 on 2023-06-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0005_club_contact1_landline_club_contact2_landline"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="additional_information",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
