# Generated by Django 4.1.1 on 2023-09-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0007_penalty"),
    ]

    operations = [
        migrations.AddField(
            model_name="penalty",
            name="season",
            field=models.ForeignKey(
                default=1999,
                on_delete=django.db.models.deletion.CASCADE,
                to="league.season",
            ),
            preserve_default=False,
        ),
    ]
