# Generated by Django 4.1.1 on 2023-09-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0009_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="penalty",
            name="penalty_value",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
