# Generated by Django 4.1.1 on 2023-09-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0010_penalty_penalty_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penalty",
            name="player",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
