# Generated by Django 4.1.1 on 2023-09-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0011_alter_penalty_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
