# Generated by Django 4.1.1 on 2023-09-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0013_alter_venue_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
