# Generated by Django 4.1.1 on 2023-09-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0014_alter_venue_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="captain_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="club",
            name="club_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
