# Generated by Django 4.1.1 on 2024-04-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0015_club_captain_notifications_club_club_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="end_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
