# Generated by Django 4.1.1 on 2024-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0017_performance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="position",
            field=models.CharField(max_length=100),
        ),
    ]
