# Generated by Django 4.1.1 on 2024-05-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0018_alter_performance_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="qualifier",
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
