# Generated by Django 4.1.1 on 2024-05-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0019_division_qualifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="division",
            name="qualifier",
        ),
        migrations.AddField(
            model_name="division",
            name="historic",
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
