# Generated by Django 4.1.1 on 2024-05-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0020_remove_division_qualifier_division_historic"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="historic_divs",
            field=models.BooleanField(default=False),
        ),
    ]
