# Generated by Django 4.1.1 on 2025-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0021_season_historic_divs"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="mixed_scoring",
            field=models.CharField(
                choices=[
                    ("point per game", "point per game"),
                    ("point per rubber", "point per rubber"),
                ],
                default="point per game",
                max_length=20,
                null=True,
            ),
        ),
    ]
