# Generated by Django 5.2.11 on 2026-03-19 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_season_mixed_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='type',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('Ladies', "Women's"), ('Mens', "Men's")], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PendingPlayerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('Mixed', 'Mixed'), ('Ladies', 'Ladies'), ('Mens', 'Mens')], max_length=10)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.fixture')),
                ('resolved_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_verifications', to='league.player')),
                ('suggested_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='league.team')),
            ],
            options={
                'unique_together': {('team', 'position', 'date_from')},
            },
        ),
    ]
