# Generated by Django 5.2.11 on 2026-03-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_alter_division_type_alter_player_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.CharField(choices=[('Ladies', "Women's"), ('Mens', "Men's")], max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('Ladies', "Women's"), ('Mens', "Men's")], max_length=10),
        ),
    ]
