# Generated by Django 5.2.11 on 2026-03-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_alter_player_level_alter_team_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamnomination',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamnomination',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingplayerverification',
            name='level',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('Ladies', "Women's"), ('Mens', "Men's")], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='teamnomination',
            unique_together={('team', 'position', 'date_from', 'approved')},
        ),
    ]
