# Generated by Django 5.2.11 on 2026-03-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0025_alter_teamnomination_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination_window_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='teamnomination',
            name='season',
        ),
    ]
