# Generated by Django 5.2.11 on 2026-04-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_leaguesettings_remove_teamnomination_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguesettings',
            options={'verbose_name_plural': 'League settings'},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'verbose_name_plural': 'Penalties'},
        ),
        migrations.AlterField(
            model_name='division',
            name='type',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('Womens', "Women's"), ('Ladies', "Ladies'"), ('Mens', "Men's")], max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingplayerverification',
            name='level',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('Ladies', "Ladies'"), ('Womens', "Women's"), ('Mens', "Men's")], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.CharField(choices=[('Ladies', "Ladies'"), ('Womens', "Women's"), ('Mens', "Men's")], max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('Womens', "Women's"), ('Ladies', "Ladies'"), ('Mens', "Men's")], max_length=10),
        ),
    ]
