# Generated by Django 5.2.11 on 2026-04-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_alter_leaguesettings_options_alter_penalty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='type',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('Womens', "Women's"), ('Mens', "Men's")], max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingplayerverification',
            name='level',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('Womens', "Women's"), ('Mens', "Men's")], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.CharField(choices=[('Womens', "Women's"), ('Mens', "Men's")], max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('Womens', "Women's"), ('Mens', "Men's")], max_length=10),
        ),
    ]
