# Generated by Django 5.2.11 on 2026-04-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0028_alter_division_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamnomination',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
