# Generated by Django 5.2.11 on 2026-04-14 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_teamnomination_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.fixture'),
        ),
    ]
