# Generated by Django 5.2.11 on 2026-04-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0030_alter_penalty_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='date_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
