# Generated by Django 5.2.11 on 2026-04-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0031_alter_fixture_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='nom_player1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='nom_player2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='nom_player3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='nom_player4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='nom_player5',
        ),
        migrations.RemoveField(
            model_name='team',
            name='nom_player6',
        ),
    ]
