# Generated by Django 4.1.1 on 2026-04-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0032_remove_team_nom_player1_remove_team_nom_player2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="division",
            name="type",
            field=models.CharField(
                choices=[
                    ("Mixed", "Mixed"),
                    ("Ladies", "Ladies"),
                    ("Womens", "Women's"),
                    ("Mens", "Men's"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="level",
            field=models.CharField(
                choices=[
                    ("Womens", "Women's"),
                    ("Ladies", "Ladies"),
                    ("Mens", "Men's"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="type",
            field=models.CharField(
                choices=[
                    ("Mixed", "Mixed"),
                    ("Womens", "Women's"),
                    ("Ladies", "Ladies"),
                    ("Mens", "Men's"),
                ],
                max_length=10,
            ),
        ),
    ]
