# Generated by Django 4.1.1 on 2026-04-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0033_alter_division_type_alter_player_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="penalties",
        ),
        migrations.AlterField(
            model_name="division",
            name="type",
            field=models.CharField(
                choices=[("Mixed", "Mixed"), ("Womens", "Women's"), ("Mens", "Men's")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="level",
            field=models.CharField(
                choices=[("Womens", "Women's"), ("Mens", "Men's")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="type",
            field=models.CharField(
                choices=[("Mixed", "Mixed"), ("Womens", "Women's"), ("Mens", "Men's")],
                max_length=10,
            ),
        ),
    ]
