# Generated by Django 5.2.11 on 2026-05-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0034_remove_team_penalties_alter_division_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
