# Generated by Django 5.2.11 on 2026-05-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0035_venue_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='home_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.venue'),
        ),
        migrations.AddField(
            model_name='team',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
