# Generated by Django 5.2.11 on 2026-05-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0036_team_end_time_team_home_venue_team_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesettings',
            name='team_selection_window_open',
            field=models.BooleanField(default=False),
        ),
    ]
