# Generated by Django 5.2.11 on 2026-05-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0037_leaguesettings_team_selection_window_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='teams_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
