# Generated by Django 5.2.11 on 2026-06-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0038_club_teams_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesettings',
            name='league_status',
            field=models.CharField(choices=[('entry', 'Team Entry'), ('fixtures', 'Fixtures and Nominations'), ('live', 'Season Live')], default='entry', max_length=10),
        ),
    ]
