# Generated by Django 5.2.11 on 2026-06-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0039_leaguesettings_league_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguesettings',
            name='nomination_window_open',
        ),
        migrations.RemoveField(
            model_name='leaguesettings',
            name='team_selection_window_open',
        ),
    ]
