# Generated by Django 5.2.11 on 2026-08-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0041_rename_mens_to_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesettings',
            name='earliest_fixture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguesettings',
            name='latest_fixture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
