# Generated by Django 5.2.11 on 2026-09-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0042_leaguesettings_earliest_fixture_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingplayerverification',
            name='player_field',
            field=models.CharField(default='away_player1', max_length=20),
            preserve_default=False,
        ),
    ]
