# Generated by Django 5.2.11 on 2026-09-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0043_pendingplayerverification_player_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingplayerverification',
            name='level',
            field=models.CharField(choices=[('Womens', "Women's"), ('Open', 'Open')], max_length=10),
        ),
    ]
